### ISSUE TITLE
safeDump returns AST data as yaml

### ISSUE THREAD

**Issue by amccloud** [mulesoft-labs/yaml-ast-parser#1]
Since safeLoad loads yaml to an AST I would expect safeDump to be the inverse.

**YAML** 

``` yaml
hello: World
```

**AST**

``` js
{ errors: [],
  startPosition: 0,
  endPosition: 12,
  mappings:
   [ { key: [Object],
       value: [Object],
       startPosition: 0,
       endPosition: 12,
       kind: 1,
       parent: [Circular],
       errors: [] } ],
  kind: 2,
  parent: null }
```

**Expected safeDump**

``` yaml
hello: World
```

**Actual safeDump**

``` yaml
&ref_1
errors: []
startPosition: 0
endPosition: 12
mappings:
  - &ref_0key:
      errors: []
      startPosition: 0
      endPosition: 5
      value: hello
      kind: 0
      parent: *ref_0
      doubleQuoted: false
      plainScalar: true
    value:
      errors: []
      startPosition: 7
      endPosition: 12
      value: World
      kind: 0
      parent: *ref_0
      doubleQuoted: false
      plainScalar: true
    startPosition: 0
    endPosition: 12
    kind: 1
    parent: *ref_1
    errors: []
kind: 2
parent: null
```
