### ISSUE TITLE
safeDump produces invalid YAML if there's an anchor in an array item

### ISSUE THREAD

**Issue by olydis** [mulesoft-labs/yaml-ast-parser#30]
I assume you basically use `safeDump` from `js-yaml`, so the bug might originate there; but here is what happens:

## Reproducing Object
``` JS
const x = {};
x.a = [{ c: 345 }];
x.b = x.a[0];
```

## `yaml-ast-parser@0.0.40` dumps
``` YAML
a:
  - &ref_0c: 345
b: *ref_0
```

## `js-yaml@3.11.0` dumps
``` YAML
a:
  - &ref_0
    c: 345
b: *ref_0
```

## Problem
Note that what `yaml-ast-parser` dumps is invalid YAML. The anchor is directly concatenated with key `c`.
